### ISSUE TITLE
Over the Lambda size limit of 250MB

### ISSUE THREAD

**Issue by hamza-sondermarketing** [tongueroo/jets-rails#10]
I have added a rails application to the jets application using Jets Afterburner mode(https://rubyonjets.com/docs/rails/afterburner/)

when I try to deploy the application using the command `jets deploy`, it is giving me the error below.
`Over the Lambda size limit of 250MB
Please reduce the size of your code.
Sizes:
Code: 0.6MB - /tmp/jets/sonder-hcm/stage/code
Gem Layer: 279.5MB - /tmp/jets/sonder-hcm/stage/opt
Total Package: 280.1MB
Over limit by: 30.1MB
Sometimes blowing away the /tmp/jets cache will reduce the size: rm -rf /tmp/jets`

Can some one please advise what to do in order to get this error fix and deploy successfully ?

**Comment by tongueroo** [comment]
Address in Jets 6 uses package type image, so it can go up to 10GB now https://blog.boltops.com/2024/05/23/ruby-on-jets-6-0-rails-support/
