### ISSUE TITLE
Rails 6 not compatible

### ISSUE THREAD

**Issue by davidplappert** [tongueroo/jets-rails#2]
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 6.0.0)

  In Gemfile:
    rails (~> 6.0.0)

    jets-rails was resolved to 0.2.0, which depends on
      rails (~> 5)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
cd /tmp/jets/globalupdateclub-api/cache && env BUNDLE_IGNORE_CONFIG=1 bundle install --path /tmp/jets/globalupdateclub-api/cache/vendor/gems --without development test failed to run.

**Comment by wowremywang** [comment]
@davidplappert have you solved this problem?

**Comment by JkRuiz** [comment]
@davidplappert same issue here, have you solved it?

**Comment by sam0x17** [comment]
Same issue here

**Comment by kokorolx** [comment]
Does it support rails 6?

**Comment by tongueroo** [comment]
Jets 6.0 supports Rails https://blog.boltops.com/2024/05/23/ruby-on-jets-6-0-rails-support/
